Repository material-components/material-components-ios, pull requests merged in 2018-05, with the labels that each got.

#3582 Revert "[Chips] Vertically center chips within available space (#3511)"
  components/Chips/examples/ChipsInputExampleViewController.m
  components/Chips/src/MDCChipField.m
Labels: [Chips], cla: yes

#3591 [schemes/Color] Update the default error color to match spec.
  components/schemes/Color/src/MDCSemanticColorScheme.m
  components/schemes/Color/tests/unit/MDCSemanticColorSchemeTests.m
Labels: cla: yes

#3603 [Buttons] Theme the typical use example with the injected schemes.
  components/Buttons/examples/ButtonsTypicalUseExampleViewController.m
Labels: [Buttons], cla: yes

#3608 [ActivityIndicator] Break the docs into separate articles and run the readme generator.
  components/ActivityIndicator/.vars
  components/ActivityIndicator/README.md
  components/ActivityIndicator/docs/README.md
  components/ActivityIndicator/docs/color-theming.md
  components/ActivityIndicator/docs/multiple-colors.md
  components/ActivityIndicator/docs/typical-use-determinate.md
  components/ActivityIndicator/docs/typical-use-indeterminate.md
Labels: cla: yes

#3611 [scripts] Ignore #\w when extracting table of content headers.
  scripts/generate_readme
Labels: cla: yes

#3610 [FlexibleHeader] Split the documentation into separate articles and run the readme generator.
  components/FlexibleHeader/.vars
  components/FlexibleHeader/README.md
  components/FlexibleHeader/docs/README.md
  components/FlexibleHeader/docs/background-images.md
  components/FlexibleHeader/docs/color-theming.md
  components/FlexibleHeader/docs/enabling-swipe-to-dismiss.md
  components/FlexibleHeader/docs/interacting-with-uinavigationcontroller.md
  components/FlexibleHeader/docs/reacting-to-frame-changes.md
  components/FlexibleHeader/docs/shift-behavior.md
  components/FlexibleHeader/docs/status-bar-style.md
  components/FlexibleHeader/docs/subclassing-considerations.md
  components/FlexibleHeader/docs/touch-forwarding.md
  components/FlexibleHeader/docs/tracking-a-parent-view.md
  components/FlexibleHeader/docs/typical-use-tracking-a-scroll-view.md
  components/FlexibleHeader/docs/typical-use.md
Labels: cla: yes

#3614 [ButtonBar] Split the documentation into separate articles and run the readme generator.
  components/ButtonBar/.vars
  components/ButtonBar/README.md
  components/ButtonBar/docs/README.md
  components/ButtonBar/docs/color-theming.md
  components/ButtonBar/docs/supported-uibarbuttonitem-properties.md
  components/ButtonBar/docs/typical-use.md
  components/ButtonBar/docs/typography-theming.md
Labels: cla: yes

#3612 [HeaderStackView] Remove color theming docs and mark the color themer as to be deprecated.
  components/HeaderStackView/README.md
  components/HeaderStackView/docs/color-theming.md
  components/HeaderStackView/src/ColorThemer/MDCHeaderStackViewColorThemer.h
Labels: cla: yes

#3600 Add documentation describing variants to buttons, chips and cards
  components/Buttons/docs/theming.md
  components/Cards/README.md
  components/Chips/README.md
Labels: cla: yes

#3599 Ensure buttons and cards reset their states correctly
  components/Buttons/src/ButtonThemer/MDCOutlinedButtonThemer.m
  components/Buttons/tests/unit/ButtonThemerTests.m
  components/Cards/src/CardThemer/MDCCardThemer.m
Labels: cla: yes

#3619 [Dialogs] Split the documentation into separate articles and run the readme generator.
  components/Dialogs/.vars
  components/Dialogs/README.md
  components/Dialogs/docs/README.md
  components/Dialogs/docs/color-theming.md
  components/Dialogs/docs/typical-use-alert.md
  components/Dialogs/docs/typical-use-modal-dialog.md
  components/Dialogs/docs/typography-theming.md
Labels: cla: yes

#3613 [Tabs] readme update.
  components/Tabs/.vars
  components/Tabs/README.md
  components/Tabs/docs/Examples.md
  components/Tabs/docs/README.md
  components/Tabs/docs/Usage.md
  components/Tabs/docs/color-theming.md
  components/Tabs/docs/typography-theming.md
Labels: cla: yes

#3607 [Typography] Add TypographyScheme example
  components/Typography/examples/TypographyCustomFontViewController.m
  components/Typography/examples/TypographyFontListExample.swift
  components/Typography/examples/TypographyMaterialStylesViewController.m
  components/Typography/examples/TypographySimpleExampleViewController.m
  components/schemes/Typography/examples/MDCTypographySchemeFontListExampleViewController.h
  components/schemes/Typography/examples/MDCTypographySchemeFontListExampleViewController.m
Labels: [Typography], cla: yes

#3620 [FeatureHighlight] Split the documentation into separate articles and run the readme generator.
  components/FeatureHighlight/.vars
  components/FeatureHighlight/README.md
  components/FeatureHighlight/docs/README.md
  components/FeatureHighlight/docs/typical-use-highlight-a-view.md
Labels: cla: yes

#3618 [Cards] Split the documentation into separate articles and run the readme generator.
  components/Cards/.vars
  components/Cards/README.md
  components/Cards/docs/README.md
  components/Cards/docs/color-theming.md
  components/Cards/docs/theming.md
  components/Cards/docs/typical-use-collections.md
  components/Cards/docs/typical-use-view.md
Labels: cla: yes

#3596 Make all of the AppBar implementation component examples be dragons.
  components/ButtonBar/examples/ButtonBarCustomizedFontExample.m
  components/ButtonBar/examples/ButtonBarIconExample.m
  components/ButtonBar/examples/ButtonBarTypicalUseExample.m
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderConfiguratorSupplemental.m
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderFABSupplemental.m
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderHorizontalPagingSupplemental.m
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderPageControlSupplemental.m
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderTopLayoutGuideSupplemental.m
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderTypicalUseSupplemental.m
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderUINavigationBarSupplemental.m
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderWrappedSupplemental.m
  components/HeaderStackView/examples/supplemental/HeaderStackViewTypicalUseSupplemental.m
  components/NavigationBar/examples/NavigationBarIconsExample.m
  components/NavigationBar/examples/NavigationBarLayoutExample.m
  components/NavigationBar/examples/NavigationBarWithBarItemsExample.m
  components/NavigationBar/examples/NavigationbarWithCustomFont.m
  components/NavigationBar/examples/supplemental/NavigationBarTypicalUseExampleSupplemental.m
Labels: cla: yes

#3622 [NavigationBar] Split the documentation into separate articles and run the readme generator.
  components/NavigationBar/.vars
  components/NavigationBar/README.md
  components/NavigationBar/docs/README.md
  components/NavigationBar/docs/color-theming.md
  components/NavigationBar/docs/observing-navigationitem-instances.md
  components/NavigationBar/docs/typography-theming.md
Labels: cla: yes

#3624 [PageControl] Split the documentation into separate articles and run the readme generator.
  components/PageControl/.vars
  components/PageControl/README.md
  components/PageControl/docs/README.md
  components/PageControl/docs/color-theming.md
  components/PageControl/docs/differences-from-uipagecontrol.md
  components/PageControl/docs/typical-use.md
Labels: cla: yes

#3623 regenerating tabs readme after file name change.
  components/Tabs/README.md
Labels: cla: yes

#3628 [Textfields] readme auto generated update.
  components/TextFields/.vars
  components/TextFields/README.md
  components/TextFields/docs/README.md
  components/TextFields/docs/classes.md
  components/TextFields/docs/color-theming.md
  components/TextFields/docs/examples.md
  components/TextFields/docs/typography-theming.md
  components/TextFields/docs/usage.md
Labels: Documentation, [TextFields], cla: yes, type:Documentation

#3630 Fix issue causing black squares on bottom sheet rotation
  components/BottomSheet/src/private/MDCDraggableView.m
Labels: cla: yes

#3626 [Slider] Split the documentation into separate articles and run the readme generator.
  components/Slider/.vars
  components/Slider/README.md
  components/Slider/docs/README.md
  components/Slider/docs/color-theming.md
  components/Slider/docs/differences-from-uislider.md
  components/Slider/docs/stateful-apis.md
  components/Slider/docs/typical-use.md
Labels: cla: yes

#3632 [NavigationBar] Fix broken link.
  components/NavigationBar/README.md
  components/NavigationBar/docs/README.md
Labels: cla: yes

#3627 [Snackbar] Split the documentation into separate articles and run the readme generator.
  components/Snackbar/.vars
  components/Snackbar/README.md
  components/Snackbar/docs/README.md
  components/Snackbar/docs/color-theming.md
  components/Snackbar/docs/typical-use-display-a-message-with-action.md
  components/Snackbar/docs/typical-use-display-a-message.md
  components/Snackbar/docs/typography-theming.md
Labels: cla: yes

#3625 [ProgressView] Split the documentation into separate articles and run the readme generator.
  components/ProgressView/.vars
  components/ProgressView/README.md
  components/ProgressView/docs/README.md
  components/ProgressView/docs/color-theming.md
  components/ProgressView/docs/differences-from-uiprogressview.md
  components/ProgressView/docs/typical-use.md
Labels: cla: yes

#3609 [schemes/Typography] Stub documentation
  components/schemes/Typography/.vars
  components/schemes/Typography/docs/README.md
Labels: cla: yes

#3637 [scripts] Hide readmes from the site if the component has no path.
  scripts/generate_readme
Labels: cla: yes

#3633 [Typography] Add deprecation notice to the MDCTypography APIs and README
  components/Typography/README.md
  components/Typography/src/MDCTypography.h
Labels: cla: yes

#3638 [ButtonBar] Remove from the website.
  components/ButtonBar/.vars
  components/ButtonBar/README.md
  components/NavigationBar/README.md
  components/NavigationBar/docs/README.md
Labels: cla: yes

#3597 [AppBar] Nest all of the implementation detail components under AppBar.
  components/HeaderStackView/.vars
  components/HeaderStackView/README.md
  components/NavigationBar/.vars
  components/NavigationBar/README.md
Labels: cla: yes

#3640 [scripts] Ensure that asset urls are remapped when generating readmes.
  components/BottomNavigation/README.md
  components/Buttons/README.md
  components/TextFields/README.md
  scripts/generate_readme
Labels: cla: yes

#3639 [Buttons] Add outlined button gif.
  components/Buttons/README.md
  components/Buttons/docs/README.md
  components/Buttons/docs/assets/outlined.gif
  components/Buttons/docs/assets/text.gif
  components/Buttons/docs/theming.md
Labels: cla: yes

#3641 [AnimationTiming] Add a gif to the readme.
  components/AnimationTiming/README.md
  components/AnimationTiming/docs/assets/animation_timing.png
  components/AnimationTiming/docs/assets/animationtiming.gif
Labels: cla: yes

#3642 [Catalog] Make many examples be dragons.
  components/BottomNavigation/examples/BottomNavigationNilBadges.swift
  components/BottomSheet/examples/supplemental/BottomSheetSupplemental.m
  components/Cards/examples/CardsCollectionExample.m
  components/Chips/examples/supplemental/ChipsExamplesSupplemental.m
  components/Dialogs/examples/supplemental/DialogDismissalOverPresentedControllerViewController.m
  components/Dialogs/examples/supplemental/DialogsKeyboardViewControllerSupplemental.m
  components/PageControl/examples/PageControlAnimationBlockExample.m
  components/PageControl/examples/PageControlButtonExample.m
  components/Palettes/examples/PalettesExpandedExample.swift
  components/Slider/examples/SliderAutolayoutExampleViewController.m
  components/Slider/examples/SliderCompareExampleViewController.m
  components/Tabs/examples/BottomNavigationBarExample.m
  components/Tabs/examples/TabBarInterfaceBuilderExample.m
  components/Tabs/examples/TabBarViewControllerInterfaceBuilderExample.m
  components/Tabs/examples/supplemental/TabBarTextOnlyExampleSupplemental.m
  components/TextFields/examples/MultilineTextFieldLegacyExample.m
  components/TextFields/examples/TextFieldManualLayoutLegacyExample.m
  components/TextFields/examples/TextFieldManualLayoutLegacyExample.swift
  components/TextFields/examples/TextFieldOutlinedExample.m
  components/TextFields/examples/supplemental/TextFieldInterfaceBuilderExampleSupplemental.m
  components/TextFields/examples/supplemental/TextFieldPresentationStylesLegacyExampleSupplemental.m
Labels: cla: yes

#3590 [Palettes] Improve example text contrast
  components/Palettes/examples/supplemental/PalettesExampleViewController.swift
Labels: Accessibility, [Palettes], cla: yes

#3636 [Themes] Add deprecation notice to APIs and remove from the site.
  components/Themes/README.md
  components/schemes/Color/src/MDCLegacyColorScheme.h
  components/schemes/Color/src/MDCLegacyTonalColorScheme.h
  components/schemes/Typography/src/MDCLegacyFontScheme.h
Labels: [Themes], cla: yes

#3617 [TextFields] fixing color mapping for floatingNormal and floatingActive Colors.
  components/TextFields/src/ColorThemer/MDCFilledTextFieldColorThemer.m
  components/TextFields/src/ColorThemer/MDCOutlinedTextFieldColorThemer.m
  components/TextFields/src/ColorThemer/MDCTextFieldColorThemer.m
  components/TextFields/tests/unit/TextFieldColorThemerTests.m
Labels: [TextFields], cla: yes

#3649 [FeatureHighlight] Allow setting accessibilityHint
  components/FeatureHighlight/examples/FeatureHighlightTypicalUseViewController.m
  components/FeatureHighlight/src/MDCFeatureHighlightViewController.m
  components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
  components/FeatureHighlight/tests/unit/FeatureHighlightAccessibilityTests.m
Labels: Accessibility, [FeatureHighlight], cla: yes

#3653 [Catalog] Set an a11y label on the menu button.
  catalog/MDCCatalog/AppDelegate.swift
Labels: cla: yes

#3647 [Chips] Replace "stroked" with "outlined" in the examples.
  components/Chips/examples/ChipsActionExampleViewController.m
  components/Chips/examples/ChipsChoiceExampleViewController.m
  components/Chips/examples/ChipsFilterExampleViewController.m
Labels: [Chips], cla: yes

#3662 Global replace of "utilize" vs "use".
  components/Cards/README.md
  components/Cards/docs/README.md
  components/Collections/src/MDCCollectionViewStyling.h
  components/Dialogs/README.md
  components/Dialogs/docs/README.md
  components/Dialogs/src/MDCDialogPresentationController.m
  components/FlexibleHeader/README.md
  components/FlexibleHeader/docs/reacting-to-frame-changes.md
  components/ShadowLayer/README.md
  components/Snackbar/src/private/MDCSnackbarOverlayView.h
  contributing/site_development.md
Labels: cla: yes

#3665 [docs] Add link to Themes docs from root docs readme.
  docs/README.md
Labels: cla: yes

#3659 [AppBar] Make the interface builder and modal presentation examples be dragons.
  components/AppBar/examples/AppBarInterfaceBuilderExampleController.m
  components/AppBar/examples/AppBarModalPresentationExample.m
Labels: cla: yes

#3669 [Theming] Link back to the scheme docs.
  docs/theming/README.md
Labels: cla: yes

#3670 [AppBar] Make the App Bar appear as "Top App Bar" in the docsite.
  components/AppBar/.vars
  components/AppBar/README.md
  components/AppBar/docs/README.md
Labels: cla: yes

#3671 [Typography] Preliminary Typography Scheme README
  components/schemes/Typography/docs/README.md
  components/schemes/Typography/src/MDCTypographyScheme.h
Labels: [Typography], cla: yes

#3672 [scripts] Add support for API list generation and improve the script's messages.
  .gitignore
  contributing/documentation.md
  scripts/generate_readme
Labels: cla: yes

#3673 Regenerate component docs with automatic API links.
  components/ActivityIndicator/.vars
  components/ActivityIndicator/README.md
  components/ActivityIndicator/docs/README.md
  components/AppBar/.vars
  components/AppBar/README.md
  components/AppBar/docs/README.md
  components/BottomAppBar/.vars
  components/BottomAppBar/README.md
  components/BottomAppBar/docs/README.md
  components/BottomNavigation/.vars
  components/BottomNavigation/README.md
  components/BottomNavigation/docs/README.md
  components/ButtonBar/.vars
  components/ButtonBar/README.md
  components/ButtonBar/docs/README.md
  components/Buttons/.vars
  components/Buttons/README.md
  components/Buttons/docs/README.md
  components/Buttons/docs/customizing-floating-action-buttons.md
  components/Cards/.vars
  components/Cards/README.md
  components/Cards/docs/README.md
  components/Chips/.vars
  components/Chips/README.md
  components/Chips/docs/README.md
  components/Dialogs/.vars
  components/Dialogs/README.md
  components/Dialogs/docs/README.md
  components/FeatureHighlight/README.md
  components/FeatureHighlight/docs/README.md
  components/FlexibleHeader/.vars
  components/FlexibleHeader/README.md
  components/FlexibleHeader/docs/README.md
  components/NavigationBar/.vars
  components/NavigationBar/README.md
  components/NavigationBar/docs/README.md
  components/PageControl/README.md
  components/PageControl/docs/README.md
  components/ProgressView/.vars
  components/ProgressView/README.md
  components/ProgressView/docs/README.md
  components/Slider/.vars
  components/Slider/README.md
  components/Slider/docs/README.md
  components/Snackbar/.vars
  components/Snackbar/README.md
  components/Snackbar/docs/README.md
  components/Tabs/.vars
  components/Tabs/README.md
  components/Tabs/docs/README.md
  components/TextFields/.vars
  components/TextFields/README.md
  components/TextFields/docs/README.md
  components/TextFields/docs/classes.md
Labels: cla: yes

#3677 [AppBar] Add animated gif to the readme.
  components/AppBar/README.md
  components/AppBar/docs/README.md
  components/AppBar/docs/assets/app_bar.png
  components/AppBar/docs/assets/top-app-bar.gif
Labels: cla: yes

#3680 Update site naming for top and bottom app bars to match spec.
  components/AppBar/.vars
  components/AppBar/README.md
  components/AppBar/docs/README.md
  components/BottomAppBar/.vars
  components/BottomAppBar/README.md
  components/BottomAppBar/docs/README.md
Labels: cla: yes

#3666 [Shapes] Added shapes documentation and linkage
  docs/README.md
  docs/supporting-shapes/README.md
  docs/supporting-shapes/assets/MDCCurvedRectShapeGenerator.png
  docs/supporting-shapes/assets/MDCPillShapeGenerator.png
  docs/supporting-shapes/assets/MDCSlantedRectShapeGenerator.png
  docs/supporting-shapes/assets/cardcellcutcorner.gif
  docs/supporting-shapes/assets/cardwithdiffcorners.gif
  docs/supporting-shapes/assets/cutcornersbutton.gif
  docs/supporting-shapes/assets/diamondfab.gif
Labels: cla: yes

#3691 Placeholder documentation for future Side Sheet component
  components/SideSheet/README.md
Labels: cla: yes

#3693 Standardize the casing for all components to match spec.
  components/ActivityIndicator/.vars
  components/ActivityIndicator/README.md
  components/ActivityIndicator/docs/README.md
  components/AnimationTiming/.vars
  components/AnimationTiming/README.md
  components/BottomNavigation/.vars
  components/BottomNavigation/README.md
  components/BottomNavigation/docs/README.md
  components/BottomSheet/.vars
  components/BottomSheet/README.md
  components/ButtonBar/.vars
  components/ButtonBar/README.md
  components/FeatureHighlight/.vars
  components/FeatureHighlight/README.md
  components/FeatureHighlight/docs/README.md
  components/FlexibleHeader/README.md
  components/FlexibleHeader/docs/README.md
  components/FlexibleHeader/docs/background-images.md
  components/FlexibleHeader/docs/interacting-with-uinavigationcontroller.md
  components/FlexibleHeader/docs/reacting-to-frame-changes.md
  components/FlexibleHeader/docs/shift-behavior.md
  components/FlexibleHeader/docs/touch-forwarding.md
  components/FlexibleHeader/docs/tracking-a-parent-view.md
  components/FlexibleHeader/docs/typical-use-tracking-a-scroll-view.md
  components/FlexibleHeader/docs/typical-use.md
  components/HeaderStackView/README.md
  components/MaskedTransition/README.md
  components/NavigationBar/.vars
  components/NavigationBar/README.md
  components/NavigationBar/docs/README.md
  components/NavigationBar/docs/observing-navigationitem-instances.md
  components/OverlayWindow/README.md
  components/PageControl/.vars
  components/PageControl/README.md
  components/PageControl/docs/README.md
  components/ProgressView/.vars
  components/ProgressView/README.md
  components/ProgressView/docs/README.md
  components/TextFields/.vars
  components/TextFields/README.md
  components/TextFields/docs/README.md
Labels: cla: yes

#3695 [Collections] Add deprecation notice to the readmes and remove from the site.
  components/CollectionCells/README.md
  components/CollectionLayoutAttributes/README.md
  components/Collections/README.md
  components/Collections/editing/README.md
  components/Collections/styling/README.md
Labels: cla: yes

#3697 [Collections] Mark all examples as dragons.
  components/CollectionCells/examples/CollectionCellsLayoutExample.m
  components/CollectionCells/examples/CollectionCellsTextExample.m
  components/Collections/examples/CollectionsALaCarteExample.m
  components/Collections/examples/CollectionsAppearanceAnimationExample.m
  components/Collections/examples/CollectionsCellAccessoryExample.m
  components/Collections/examples/CollectionsCellColorExample.m
  components/Collections/examples/CollectionsCellSeparatorExample.m
  components/Collections/examples/CollectionsContainerExample.m
  components/Collections/examples/CollectionsEditingExample.m
  components/Collections/examples/CollectionsGridExample.m
  components/Collections/examples/CollectionsHeaderFooterExample.m
  components/Collections/examples/CollectionsInkExample.m
  components/Collections/examples/CollectionsInlayExample.m
  components/Collections/examples/CollectionsSimpleDemo.m
  components/Collections/examples/CollectionsSimpleSwiftDemo.swift
  components/Collections/examples/CollectionsStoryboardExample.m
  components/Collections/examples/CollectionsSwipeToDismissRowExample.m
  components/Collections/examples/CollectionsSwipeToDismissSectionExample.m
  components/Collections/examples/supplemental/CollectionsEditingManyCellsExampleSupplemental.m
  components/Collections/examples/supplemental/CollectionsSectionInsetsExampleSupplemental.m
Labels: cla: yes

#3700 [Cards] Fix examples and themer
  components/Cards/examples/EditReorderCollectionViewController.swift
  components/Cards/src/CardThemer/MDCCardThemer.m
  components/Cards/src/ColorThemer/MDCCardsColorThemer.m
Labels: cla: yes

#3701 Fix broken link in README.md
  docs/tutorial/README.md
Labels: cla: yes

#3722 Remove outdated tutorial
  README.md
  docs/README.md
  docs/docsite-index.md
  docs/tutorial/README.md
  docs/tutorial/docs/assets/App-Collection-No-AppBar.gif
  docs/tutorial/docs/assets/App-Collection-No-Flexing.gif
  docs/tutorial/docs/assets/App-Collection-With-Bar-Button.gif
  docs/tutorial/docs/assets/App-Collection-With-Flexing.gif
  docs/tutorial/docs/assets/App-Complete.gif
  docs/tutorial/docs/assets/Pesto.gif
  docs/tutorial/docs/assets/Shrine.gif
  docs/tutorial/docs/assets/Terminal-Pod-Installation.jpg
  docs/tutorial/docs/assets/Xcode-Class-Import-and-Subclass.gif
  docs/tutorial/docs/assets/Xcode-Select-File.gif
  docs/tutorial/docs/assets/Xcode-Storyboard-Define-Cell.jpg
  docs/tutorial/docs/assets/Xcode-Storyboard-Define-Cell.m4v
  docs/tutorial/docs/assets/Xcode-Storyboard-Replace-Controller.jpg
  docs/tutorial/docs/assets/Xcode-Storyboard-Replace-Controller.m4v
Labels: cla: yes

#3733 [Cards] 'Edit' button should show action, not state
  components/Cards/examples/EditReorderCollectionViewController.swift
Labels: [Cards], cla: yes

#3736 [Dialogs] Make "modal" dialog "non-dismissable"
  components/Dialogs/examples/DialogsTypicalUseViewController.m
Labels: [Dialogs], cla: yes

#3734 [BottomAppBar] Make FAB visibility a switch
  components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.m
Labels: [BottomAppBar], cla: yes

#3738 [Catalog] FeatureHighlight should be themed according to global theming.
  components/FeatureHighlight/examples/FeatureHighlightShownViewExample.m
  components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.h
  components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m
Labels: cla: yes

#3737 [Catalog] Shaped Buttons should be all themed using global themes.
  components/Buttons/examples/ButtonsShapesExampleViewController.m
Labels: cla: yes

#3740 [Catalog] Bottom App bar should theme the FAB Button.
  components/BottomAppBar/examples/BottomAppBarTypicalUseExample.m
  components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseViewController.m
Labels: cla: yes

#3739 [Tabs] "Add" button shows when needed
  components/Tabs/examples/TabBarIconExample.m
  components/Tabs/examples/supplemental/TabBarIconExampleSupplemental.m
Labels: [Tabs], cla: yes

#3743 [Catalog] FeatureHighlight Colors Should be a dragon example.
  components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m
Labels: cla: yes

#3741 [Shadow Elevation] Changed slider to be discrete to make it clear
  components/ShadowElevations/examples/ShadowElevationsTypicalUseExample.m
Labels: cla: yes

#3747 [Catalog] Finish menu functionality and placement
  catalog/MDCCatalog/MDCCatalogComponentsController.swift
  catalog/MDCCatalog/MDCCatalogDebugAlert.swift
  catalog/MDCCatalog/MDCCatalogWindow.swift
  catalog/MDCCatalog/MDCMenuViewController.swift
Labels: (Catalog), cla: yes

#3753 [Catalog] New layout for the catalog flexible header to have button and logo stay on screen when scrolling
  catalog/MDCCatalog/AppTheme.swift
  catalog/MDCCatalog/MDCCatalogComponentsController.swift
Labels: cla: yes

#3755 Add initial danger CI script.
  .gitignore
  .kokoro
  dangerfile.js
  package.json
Labels: cla: yes

#3757 [kokoro] Add danger support.
  .gitignore
  .kokoro
  dangerfile.js
  package.json
Labels: cla: yes

#3744 [Catalog] Fix component list header section insets on iPhone X.
  catalog/MDCCatalog/MDCNodeListViewController.swift
Labels: cla: yes

#4149 [kokoro] Fix import statement rewrite behavior.
  .kokoro
Labels: cla: yes

#4151 [schemes] Fix docsite generation due to missing and malformed metadata.
  components/schemes/Bidirectionality/README.md
  components/schemes/Color/.jazzy.yaml
  components/schemes/Typography/.jazzy.yaml
Labels: cla: yes

#3760 [BottomAppBar] Add an app bar to the bottom app bar demo
  components/BottomAppBar/examples/BottomAppBarTypicalUseExample.m
  components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.h
  components/BottomAppBar/examples/supplemental/BottomAppBarTypicalUseSupplemental.m
Labels: cla: yes

#4153 [Buttons] Fix updateTitles to prevent crash
  components/Buttons/src/MDCButton.m
  components/Buttons/tests/unit/ButtonsTests.m
Labels: [Buttons], cla: yes

#3754 [FlexibleHeader] Fixed behavior for top layout guide and safe area insets.
  .kokoro
  components/FlexibleHeader/examples/FlexibleHeaderTopLayoutGuideExample.m
  components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.h
  components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m
  components/FlexibleHeader/src/MDCFlexibleHeaderViewController.h
  components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m
  components/FlexibleHeader/tests/unit/FlexibleHeaderInjectionTopLayoutGuideTests.swift
  components/FlexibleHeader/tests/unit/FlexibleHeaderViewControllerTopLayoutGuideTests.m
  components/FlexibleHeader/tests/unit/FlexibleHeaderWrappingLegacyTopLayoutGuideTests.swift
  components/FlexibleHeader/tests/unit/FlexibleHeaderWrappingTopLayoutGuideTests.swift
Labels: cla: yes

#4164 [scripts/release] Add support for generating API diffs to an arbitrary sha.
  scripts/release
Labels: cla: yes

#4168 [Snackbar] Add a +hasMessagesShowingOrQueued class method
  components/Snackbar/src/MDCSnackbarManager.h
  components/Snackbar/src/MDCSnackbarManager.m
  components/Snackbar/tests/unit/SnackbarManagerSwiftTests.swift
  components/Snackbar/tests/unit/SnackbarManagerTests.m
Labels: cla: yes

#3742 [Catalog] Feature highlight should be triggered from a separate Button.
  components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.h
  components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m
Labels: cla: yes

#4169 [kokoro] Add a stub apidiff command for the apidiff CI job.
  .kokoro
Labels: cla: yes

#4155 [danger] Add a check for changes that affect multiple components.
  dangerfile.js
Labels: cla: yes

#4175 [FeatureHighlight] title not attributed.
  components/FeatureHighlight/src/MDCFeatureHighlightViewController.m
Labels: [FeatureHighlight], cla: yes

#4188 [Lists] fix analyze warnings from example
  components/List/examples/CollectionListCellExampleTypicalUse.m
Labels: [Lists], cla: yes

#4171 [Snackbar] Exposed the snackbar button class
  components/Snackbar/examples/SnackbarSimpleExample.m
  components/Snackbar/examples/supplemental/SnackbarExampleSupplemental.h
  components/Snackbar/src/MDCSnackbarManager.h
  components/Snackbar/src/MDCSnackbarManager.m
  components/Snackbar/src/MDCSnackbarMessageView.h
  components/Snackbar/src/MDCSnackbarMessageView.m
Labels: [Snackbar], cla: yes

#4194 [ShadowElevations] Expose BottomNavigationBar elevation
  components/ShadowElevations/src/MDCShadowElevations.h
Labels: [ShadowElevations], cla: yes

#4157 [Buttons] Disable flaky test.
  components/Buttons/tests/unit/FloatingButtonTests.m
Labels: cla: yes

#4196 [TextFields] Getting rid of paddedLabel Class since it's not needed anymore.
  components/TextFields/src/MDCTextInputControllerOutlined.m
  components/TextFields/src/private/MDCPaddedLabel.h
  components/TextFields/src/private/MDCPaddedLabel.m
  components/TextFields/src/private/MDCTextInputCommonFundament.m
Labels: [TextFields], cla: yes

#4210 Add team handbook bug template
  .github/ISSUE_TEMPLATE/Team_handbook.md
Labels: cla: yes

#4200 [Catalog]Initialize default color and typography schemes in examples
  components/ActivityIndicator/examples/ActivityIndicatorExample.m
  components/ActivityIndicator/examples/ActivityIndicatorTransitionExample.m
  components/AppBar/examples/AppBarImageryExample.m
  components/AppBar/examples/AppBarInterfaceBuilderExampleController.m
  components/AppBar/examples/AppBarModalPresentationExample.m
  components/AppBar/examples/AppBarSectionHeadersExample.m
  components/AppBar/examples/AppBarTypicalCollectionViewExample.m
  components/AppBar/examples/AppBarTypicalUseExample.m
  components/ButtonBar/examples/ButtonBarCustomizedFontExample.m
  components/ButtonBar/examples/ButtonBarTypicalUseExample.m
  components/Buttons/examples/ButtonsShapesExampleViewController.m
  components/Buttons/examples/ButtonsTypicalUseExampleViewController.m
  components/Buttons/examples/FloatingButtonExampleViewController.m
  components/Chips/examples/ChipsActionExampleViewController.m
  components/Chips/examples/ChipsChoiceExampleViewController.m
  components/Chips/examples/ChipsFilterExampleViewController.m
  components/Chips/examples/ChipsInputExampleViewController.m
  components/Chips/examples/ChipsTypicalUseViewController.m
  components/Dialogs/examples/DialogsAlertViewController.m
  components/Dialogs/examples/DialogsTypicalUseViewController.m
  components/FeatureHighlight/examples/FeatureHighlightShownViewExample.m
  components/FeatureHighlight/examples/FeatureHighlightTypicalUseViewController.m
  components/NavigationBar/examples/NavigationBarIconsExample.m
  components/NavigationBar/examples/NavigationBarLayoutExample.m
  components/NavigationBar/examples/NavigationBarTypicalUseExample.m
  components/NavigationBar/examples/NavigationBarWithBarItemsExample.m
  components/NavigationBar/examples/NavigationbarWithCustomFont.m
  components/Slider/examples/SliderAutolayoutExampleViewController.m
  components/Slider/examples/SliderCollectionViewController.m
  components/Slider/examples/SliderCompareExampleViewController.m
  components/Tabs/examples/BottomNavigationBarExample.m
  components/Tabs/examples/TabBarIconExample.m
  components/Tabs/examples/TabBarInterfaceBuilderExample.m
  components/Tabs/examples/TabBarTextOnlyExample.m
  components/Tabs/examples/TabBarViewControllerExample.m
  components/Tabs/examples/TabBarViewControllerInterfaceBuilderExample.m
  components/schemes/Typography/examples/MDCTypographySchemeFontListExampleViewController.m
Labels: cla: yes

#4198 [Typography] Add unit test to improve coverage
  components/Typography/BUILD
  components/Typography/tests/unit/TypographyTests.m
Labels: Testing, [Typography], cla: yes

#4181 [kokoro] Adding new apidiff script.
  .kokoro
  scripts/github-comment/.gitignore
  scripts/github-comment/Package.resolved
  scripts/github-comment/Package.swift
  scripts/github-comment/Sources/github-comment/github/GitHub.swift
  scripts/github-comment/Sources/github-comment/github/GitHubAPI.swift
  scripts/github-comment/Sources/github-comment/github/GitHubComments.swift
  scripts/github-comment/Sources/github-comment/github/GitHubUsers.swift
  scripts/github-comment/Sources/github-comment/github/Networking.swift
  scripts/github-comment/Sources/github-comment/main.swift
Labels: Scripts, cla: yes

#4170 [FlexibleHeader] Always update opacity for views that hide when shifted.
  components/FlexibleHeader/examples/supplemental/FlexibleHeaderConfiguratorSupplemental.m
  components/FlexibleHeader/src/MDCFlexibleHeaderView.m
Labels: cla: yes

#4197 [AppBar] Create an example of MDCAppBarContainerViewController usage
  components/AppBar/examples/AppBarWrappedExample.m
Labels: [AppBar], cla: yes

#4245 [kokoro] Add new apidiff CI command.
  .kokoro
  scripts/github-comment/.gitignore
  scripts/github-comment/Package.resolved
  scripts/github-comment/Package.swift
  scripts/github-comment/Sources/github-comment/github/GitHub.swift
  scripts/github-comment/Sources/github-comment/github/GitHubAPI.swift
  scripts/github-comment/Sources/github-comment/github/GitHubComments.swift
  scripts/github-comment/Sources/github-comment/github/GitHubUsers.swift
  scripts/github-comment/Sources/github-comment/github/Networking.swift
  scripts/github-comment/Sources/github-comment/main.swift
Labels: cla: yes

#4249 [TextFields] Fix notification parameter type
  components/TextFields/src/MDCMultilineTextField.m
Labels: [TextFields], cla: yes

#4238 [Dialogs] Setting Properties on Alert controller will not force the view to load.
  components/Dialogs/src/MDCAlertController.m
  components/Dialogs/tests/unit/MDCAlertControllerTests.m
Labels: [Dialogs], cla: yes

#4233 [Dialogs] Add customizable cornerRadius to enable proper shadowing
  components/Dialogs/examples/DialogsCustomShadowViewController.swift
  components/Dialogs/src/MDCDialogPresentationController.h
  components/Dialogs/src/MDCDialogPresentationController.m
Labels: [Dialogs], cla: yes

#4234 [FeatureHighlight] View should not be loaded unless it's explicitly called or presented.
  components/FeatureHighlight/src/FeatureHighlightAccessibilityMutator/MDCFeatureHighlightAccessibilityMutator.m
  components/FeatureHighlight/src/MDCFeatureHighlightViewController.h
  components/FeatureHighlight/src/MDCFeatureHighlightViewController.m
  components/FeatureHighlight/src/MaterialFeatureHighlightStrings.h
  components/FeatureHighlight/src/MaterialFeatureHighlightStrings_table.h
  components/FeatureHighlight/src/private/MDCFeatureHighlightView+Private.m
  components/FeatureHighlight/tests/unit/FeatureHighlightAccessibilityTests.m
  components/FeatureHighlight/tests/unit/FeatureHighlightTitleBodyAccessibilityMutatorTests.m
  components/FeatureHighlight/tests/unit/FeatureHighlightViewControllerTests.m
Labels: [FeatureHighlight], cla: yes

#4241 [BottomSheet] Fix layout issues caused by invoking self.dismissOnBackgroundTap in -init
  components/BottomSheet/src/MDCBottomSheetController.m
Labels: [BottomSheet], cla: yes

#4268 [BottomSheet] Add an app bar to the typical use example.
  components/BottomSheet/examples/BottomSheetTypicalUseExample.m
  components/BottomSheet/examples/supplemental/BottomSheetPresenterViewController.h
  components/BottomSheet/examples/supplemental/BottomSheetPresenterViewController.m
Labels: [BottomSheet], cla: yes

#4274 [TextFields] Fix text area placeholder
  components/TextFields/examples/TextFieldFilledExample.swift
  components/TextFields/examples/TextFieldOutlinedExample.m
  components/TextFields/src/MDCTextInputControllerOutlinedTextArea.m
Labels: [TextFields], cla: yes

#4279 [Catalog] Update CbC for our targets to the new version (2.5.0)
  catalog/Podfile
Labels: [Catalog], cla: yes

#4278 [Docs] Add badges to all components.
  components/ActivityIndicator/README.md
  components/ActivityIndicator/docs/README.md
  components/AppBar/README.md
  components/AppBar/docs/README.md
  components/BottomAppBar/README.md
  components/BottomAppBar/docs/README.md
  components/BottomNavigation/README.md
  components/BottomNavigation/docs/README.md
  components/ButtonBar/README.md
  components/ButtonBar/docs/README.md
  components/Buttons/README.md
  components/Buttons/docs/README.md
  components/Cards/README.md
  components/Cards/docs/README.md
  components/Chips/README.md
  components/Chips/docs/README.md
  components/Dialogs/README.md
  components/Dialogs/docs/README.md
  components/FeatureHighlight/README.md
  components/FeatureHighlight/docs/README.md
  components/FlexibleHeader/README.md
  components/FlexibleHeader/docs/README.md
  components/NavigationBar/README.md
  components/NavigationBar/docs/README.md
  components/PageControl/README.md
  components/PageControl/docs/README.md
  components/ProgressView/README.md
  components/ProgressView/docs/README.md
  components/Slider/README.md
  components/Slider/docs/README.md
  components/Snackbar/README.md
  components/Snackbar/docs/README.md
  components/Tabs/README.md
  components/Tabs/docs/README.md
  components/TextFields/README.md
  components/TextFields/docs/README.md
  contributing/documentation.md
  scripts/generate_all_readmes
  scripts/generate_readme
Labels: [ActivityIndicator], [AppBar], [BottomAppBar], [BottomNavigation], [ButtonBar], [Buttons], [Cards], [Chips], [Dialogs], [FeatureHighlight], [FlexibleHeader], [NavigationBar], [PageControl], [ProgressView], [Slider], [Snackbar], [Tabs], [TextFields], cla: yes

#4281 [TextFields] Correcting copy mistake.
  components/TextFields/examples/TextFieldFilledExample.swift
  components/TextFields/examples/TextFieldOutlinedExample.m
Labels: [TextFields], cla: yes

#4295 [TextFields] Documentation update
  components/TextFields/README.md
  components/TextFields/styling/README.md
Labels: [TextFields], cla: yes

#4297 [TextFields] Corrects obscure multiline height bug
  components/TextFields/src/MDCMultilineTextField.m
Labels: [TextFields], cla: yes

#4213 [TextFields] Floating placeholder font changes after users starts typing.
  components/TextFields/src/MDCTextInputControllerBase.m
  components/TextFields/src/MDCTextInputControllerFullWidth.m
  components/TextFields/tests/unit/TextInputControllerBaseTests.m
Labels: Visible bug, [TextFields], cla: yes, type:Bug

#4300 [FeatureHighlight] Fixing the issue with broken rotation placement for FeatureHighlight.
  components/FeatureHighlight/src/MDCFeatureHighlightViewController.m
Labels: [FeatureHighlight], cla: yes

#4291 [Dialogs] AlertController button layout issue
  components/Dialogs/src/private/MDCAlertControllerView+Private.m
Labels: [Dialogs], cla: yes

#4294 [kokoro] Make the private component rewrite rules more generic.
  .kokoro
Labels: cla: yes

#4310 Update releasing.md
  contributing/releasing.md
Labels: cla: yes

#4214 [FlexibleHeader] Fixed behavior for top layout guide and safe area insets.
  components/FlexibleHeader/examples/FlexibleHeaderTopLayoutGuideExample.m
  components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.h
  components/FlexibleHeader/src/MDCFlexibleHeaderContainerViewController.m
  components/FlexibleHeader/src/MDCFlexibleHeaderViewController.h
  components/FlexibleHeader/src/MDCFlexibleHeaderViewController.m
  components/FlexibleHeader/tests/unit/FlexibleHeaderInjectionLegacyTopLayoutGuideTests.swift
  components/FlexibleHeader/tests/unit/FlexibleHeaderInjectionTopLayoutGuideTests.swift
  components/FlexibleHeader/tests/unit/FlexibleHeaderViewControllerTopLayoutGuideTests.m
  components/FlexibleHeader/tests/unit/FlexibleHeaderWrappingLegacyTopLayoutGuideTests.swift
  components/FlexibleHeader/tests/unit/FlexibleHeaderWrappingTopLayoutGuideTests.swift
Labels: [FlexibleHeader], cla: yes

#4313 [scripts] Add a squash-and-merge Chrome extension.
  scripts/github-squash-and-merge/README.md
  scripts/github-squash-and-merge/main.js
  scripts/github-squash-and-merge/manifest.json
Labels: cla: yes

#4328 Remove the GitHub squash-and-merge Chrome extension
  scripts/github-squash-and-merge/README.md
  scripts/github-squash-and-merge/main.js
  scripts/github-squash-and-merge/manifest.json
Labels: cla: yes

#4322 [Docs] Minor update to the release doc.
  contributing/releasing.md
Labels: cla: yes

#4187 [Catalog] Apply updates to catalog spacing, labels, and cell styles
  catalog/MDCCatalog/MDCCatalogCollectionViewCell.swift
  catalog/MDCCatalog/MDCNodeListViewController.swift
Labels: [Catalog], cla: yes

#4327 [Slider]Fix accessibilityIncrement for discrete sliders
  components/Slider/src/MDCSlider.m
  components/Slider/tests/unit/SliderTests.m
Labels: [Slider], cla: yes
